import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProviders } from "@/providers/ChakraProvider";
import Header from "@/components/Headers/Header";
import PrimeProvider from "@/providers/PrimeProvider";
import ReduxProvider from "@/providers/ReduxProvider";
import QueryProvider from "@/providers/QueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <QueryProvider>
            <ChakraProviders>
              <PrimeProvider>
                <Header />
                {children}
              </PrimeProvider>
            </ChakraProviders>
          </QueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
